---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2802689258-rY44BP1gq85LHTW0KR4PUluwbvZKUHcizXbOkzn
:access_token_secret: TqsoIwesdV3VHztyXyheJ1b3LtgsHDm11c2VSczsc2pGL
